version: '3.8'

services:
 db:
  image: postgres:15
  container_name: certificados_postgres
  restart: always
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: login
   POSTGRES_DB: api
  ports:
   - "5432:5432"
  volumes:
   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  networks:
   - app-network

networks:
 app-network:
  external: true
